services:
  when:
    build: .
    ports:
      - "3000:80"
    environment:
      - CONVEX_URL=${CONVEX_URL}
      - CONVEX_SITE_URL=${CONVEX_SITE_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    restart: unless-stopped
