import { useEffect } from "react";
import { TOKEN_KEY, OAUTH_NONCE_KEY, validateGoogleJwt } from "../lib/googleAuth";

/**
 * Route component mounted at /auth/callback.
 *
 * After the Convex HTTP endpoint exchanges the Google authorization code for
 * an ID token, it redirects the browser here with the token and state in the
 * URL fragment:
 *
 *   /auth/callback#token=<jwt>&redirect=<nonce|path>
 *
 * This component:
 * 1. Verifies the CSRF nonce against sessionStorage (prevents session fixation)
 * 2. Validates the JWT structure and claims (defense-in-depth)
 * 3. Stores the token in localStorage
 * 4. Navigates to the original page via full-page load so the
 *    GoogleAuthProvider re-initialises with the fresh token
 */
export function AuthCallbackPage() {
  useEffect(() => {
    const hash = window.location.hash.substring(1);
    const params = new URLSearchParams(hash);
    const token = params.get("token");
    const fullState = params.get("redirect") || "/";

    // ── CSRF nonce verification ──────────────────────────────────────────
    // The state parameter is formatted as "nonce|redirectPath". The nonce
    // was generated by signIn() and stored in sessionStorage (per-tab,
    // same-origin). An attacker cannot read or set sessionStorage for our
    // origin, so a mismatch means this callback was not initiated by us.
    const pipeIndex = fullState.indexOf("|");
    const nonce = pipeIndex >= 0 ? fullState.substring(0, pipeIndex) : "";
    const redirect =
      pipeIndex >= 0 ? fullState.substring(pipeIndex + 1) : fullState;

    const storedNonce = sessionStorage.getItem(OAUTH_NONCE_KEY);
    sessionStorage.removeItem(OAUTH_NONCE_KEY);

    if (!storedNonce || nonce !== storedNonce) {
      console.warn(
        "OAuth CSRF verification failed — nonce mismatch. " +
          "Possible session-fixation attempt. Discarding token.",
      );
      window.location.replace("/");
      return;
    }

    // ── Token validation & storage ───────────────────────────────────────
    if (token) {
      if (validateGoogleJwt(token)) {
        localStorage.setItem(TOKEN_KEY, token);
      } else {
        console.warn(
          "Received Google ID token failed client-side validation. " +
            "Discarding token.",
        );
      }
    }

    // Full navigation (not pushState) so every provider re-reads localStorage
    window.location.replace(redirect || "/");
  }, []);

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50 dark:bg-slate-900">
      <span className="text-gray-500 dark:text-slate-400">Signing in...</span>
    </div>
  );
}
